---
title: "ÖGD_Netzwerk"
author: "Jakob Schumacher"
date: "24 März 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressWarnings(suppressMessages(library(igraph)))
suppressWarnings(suppressMessages(library(dplyr)))
suppressWarnings(suppressMessages(library(networkD3)))
setwd(here::here())
```


```{r}
nodes <- read.csv("nodes.csv", sep = ",")
# nodes$name <- as.integer(nodes$name)
nodes$membership <- nodes$group
nodes$group <- NULL

edges <- read.csv("edges_schumacher.csv", sep = ",")

edges <- edges %>% 
  mutate(value = ifelse(value > 3, value, NA)) %>% 
  na.omit()

```


```{r}
forceNetwork(Links = "edges", 
             Nodes = "nodes", 
             Source = "source",
             Target = "target", 
             Value = "value", 
             NodeID = "name", 
             Nodesize = "size", 
             membership = "groups",  
             opacity = 0.4)
```



```{r}
net <- graph_from_data_frame(d = edges, vertices = nodes, directed = F) 

E(net)$weight <- edges$value

V(net)$size <- 10^V(net)$size

plot(net, 
     vertex.label.color = "black", 
     vertex.label.dist = 1,
     vertex.size = 7,
     main = "ÖGD Netzwerk")


```


# Der ÖGD ist ein Teil des Gesundheitswesens

# Weight = Jährliche Anzahl der Kontakt bei denen eine relevante Information ausgetauscht wird




```{r}
# Load data
data(MisLinks)
data(MisNodes)

# Plot
forceNetwork(Links = MisLinks, Nodes = MisNodes,
            Source = "source", Target = "target",
            Value = "value", NodeID = "name",
            Group = "group", opacity = 0.8)
```



```{r}
netd3 <- igraph_to_networkD3(net, group = membership)
# forceNetwork(Links = netd3$links, Nodes = netd3$nodes, Source = 'source', Target = 'target', NodeID = 'name')
```


```{r}
# Create edge list out of node list
# edges <- expand.grid(nodes$Abkuerzung, nodes$Abkuerzung)  
# edges <- edges[order(edges$Var1),]
# edges <- edges[duplicated(t(apply(edges, 1, sort))),]
# write.csv(edges, file = "edges.csv")
```

