---
title: "ÖGD_Netzwerk"
author: "Jakob Schumacher"
date: "24 März 2019"
output: html_document
---

```{r setup}
suppressWarnings(suppressMessages(library(igraph)))
suppressWarnings(suppressMessages(library(tidyverse)))
suppressWarnings(suppressMessages(library(networkD3)))
setwd(here::here("oegd_network"))
```


```{r}
# Read in data
nodes <- read.csv("nodes_schumacher.csv", sep = ",")
edges <- read.csv("edges_schumacher.csv", sep = ",")


# Umwandeln der Namen der Nodes in Ziffern
nodes$id <- c(0:(nrow(nodes) - 1))


# Source und Target durch ID ersetzen
edges <- edges %>% 
  left_join(nodes %>% 
              select(name, id) %>% 
              rename(source = name), by = "source") %>% 
  select(source = id, value, target) %>% 
    left_join(nodes %>% 
              select(name, id) %>% 
              rename(target = name), by = "target") %>% 
  select(source, target = id, value) 

# Cut-off für edges$value
edges <- edges %>% 
  mutate(value = ifelse(value > 4, value, NA)) %>% 
  na.omit()

nodes <- nodes %>% 
  select(id, size, group, fullname )

```


```{r}
# Netzwerk erstellen
oegd_network <- forceNetwork(Links = edges, 
             Nodes = nodes,
            Source = "source", 
            Target = "target",
            Value = "value", 
            NodeID = "fullname",
            Group = "group", 
            fontSize = 50,
            opacity = 0.8,
            linkWidth = JS("function(d) { return d.value/10; }"),
            Nodesize = "size",
            radiusCalculation = JS("Math.pow(2, d.nodesize)"),
            charge = -3000,
            zoom = TRUE) 

# Beschreibung hinzufügen
oegd_network <- oegd_network %>% 
  htmlwidgets::prependContent(htmltools::tags$h1("ÖGD-Netzwerk")) %>% 
  htmlwidgets::prependContent(htmltools::tags$p("Knoten = durch Jakob Schumacher geschätzten Anzahl aller Mitarbeitenden der Einrichtung. Größenformel= 2^10log(Anzahl)")) %>%  
  htmlwidgets::prependContent(htmltools::tags$p("Links = durch Jakob Schumacher geschätzte jährliche Anzahl der Kontakt bei denen eine relevante Information ausgetauscht wird. Größenformel = Anzahl/10")) %>% 
  htmlwidgets::prependContent(htmltools::tags$p("Zoom mit Strg + Mausrad")) 

# Netzwerk speichern
#oegd_network
saveNetwork(oegd_network, file = 'index.html')

```




```{r, eval=FALSE}
library(ggmap)
data <- read_csv("noeg.csv")


locations <- data %>% 
  mutate_geocode(Name)

locations %>% na.omit()
class(data)

mutate_geocode("Bundesministerium für Gesundheit")


df <- data.frame(
  address = c("1600 Pennsylvania Avenue, Washington DC", "", "houston texas"),
  stringsAsFactors = FALSE
)

## Not run:  # Server response can be slow; this cuts down check time.
mutate_geocode(df, address)


library(dplyr)
df %>% mutate_geocode(address)

## End(Not run)

```

